# Generated by Django 3.2.9 on 2021-11-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
            ],
        ),
    ]
