# Generated by Django 3.2.9 on 2021-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.CharField(default='/images/', max_length=200),
            preserve_default=False,
        ),
    ]
