# Generated by Django 3.2.9 on 2021-12-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_player_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img_loc',
            field=models.ImageField(blank=True, null=True, upload_to='images1/'),
        ),
    ]
